# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Anemone"
license = "MIT"
licenselink = "https://github.com/Valac01/hugo-anemone/blob/main/LICENSE"
description = ""
homepage = "https://github.com/Valac01/hugo-anemone"
tags = ["blog"]
features = []
min_version = "0.83.1"

[author]
  name = "Barish Barla"
  homepage = "https://github.com/Valac01/"
