baseURL = "/"
languageCode = "en-us"
title = "Anemone"
theme = "Anemone"
copyright = "Anemone."

enableRobotsTXT = true

[markup.highlight]
codeFences = true
noClasses = true
style = "base16-snazzy"

[[module.mounts]]
  source = "static/covers"
  target = "assets/covers"

[[params.nav.custom]]
title = "Home"
url = "/"

[[params.nav.custom]]
title = "Blog"
url = "/posts"

[[params.nav.custom]]
title = "Sample Drafts"
url = "/drafts"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.latest.section]]
title = "Latest Blog Posts"
url = "/posts"

[[params.latest.section]]
title = "Drafts"
url = "/drafts"

[[params.latest.section]]
title = "Notes"
url = "/notes"

[frontmatter]
  lastmod = [":fileModTime", ":default"]